.PHONY: clean All

All:
	@echo "----------Building project:[ trees_and_subway - Debug ]----------"
	@cd "D:\OneDrive\Study\MOOC\Coursera\Programming_and_Algorithm\01Introduction_to_Computation_and_C_programming\trees_and_subway" && "$(MAKE)" -f  "trees_and_subway.mk"
clean:
	@echo "----------Cleaning project:[ trees_and_subway - Debug ]----------"
	@cd "D:\OneDrive\Study\MOOC\Coursera\Programming_and_Algorithm\01Introduction_to_Computation_and_C_programming\trees_and_subway" && "$(MAKE)" -f  "trees_and_subway.mk" clean
