.PHONY: clean All

All:
	@echo "----------Building project:[ self_divisor - Debug ]----------"
	@cd "D:\OneDrive\Study\MOOC\Coursera\Programming_and_Algorithm\01Introduction_to_Computation_and_C_programming\self_divisor" && "$(MAKE)" -f  "self_divisor.mk"
clean:
	@echo "----------Cleaning project:[ self_divisor - Debug ]----------"
	@cd "D:\OneDrive\Study\MOOC\Coursera\Programming_and_Algorithm\01Introduction_to_Computation_and_C_programming\self_divisor" && "$(MAKE)" -f  "self_divisor.mk" clean
