.PHONY: clean All

All:
	@echo "----------Building project:[ string_insertion - Debug ]----------"
	@cd "D:\OneDrive\Study\MOOC\Coursera\Programming_and_Algorithm\01Introduction_to_Computation_and_C_programming\string_insertion" && "$(MAKE)" -f  "string_insertion.mk"
clean:
	@echo "----------Cleaning project:[ string_insertion - Debug ]----------"
	@cd "D:\OneDrive\Study\MOOC\Coursera\Programming_and_Algorithm\01Introduction_to_Computation_and_C_programming\string_insertion" && "$(MAKE)" -f  "string_insertion.mk" clean
