.PHONY: clean All

All:
	@echo "----------Building project:[ tomorrow_never_knows - Debug ]----------"
	@cd "tomorrow_never_knows" && "$(MAKE)" -f  "tomorrow_never_knows.mk"
clean:
	@echo "----------Cleaning project:[ tomorrow_never_knows - Debug ]----------"
	@cd "tomorrow_never_knows" && "$(MAKE)" -f  "tomorrow_never_knows.mk" clean
