.PHONY: clean All

All:
	@echo "----------Building project:[ match_base_chain - Debug ]----------"
	@cd "match_base_chain" && "$(MAKE)" -f  "match_base_chain.mk"
clean:
	@echo "----------Cleaning project:[ match_base_chain - Debug ]----------"
	@cd "match_base_chain" && "$(MAKE)" -f  "match_base_chain.mk" clean
