.PHONY: clean All

All:
	@echo "----------Building project:[ typesetting - Debug ]----------"
	@cd "typesetting" && "$(MAKE)" -f  "typesetting.mk"
clean:
	@echo "----------Cleaning project:[ typesetting - Debug ]----------"
	@cd "typesetting" && "$(MAKE)" -f  "typesetting.mk" clean
